on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:

name: ci

jobs:
  test_and_publish_docker_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - run: npm ci

      - run: npm run lint
      - run: npm run test

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: italia/developers-italia-onboarding:staging
